# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c9b69f2670a2a5db8a254ed6d5195c17b67bea2e21f9d9c8b5dc42e87b6e86d6b116d7a53848d2ad0cb8d0c13a2f38d13b159ae3288ee576e676c3e7e395e48

test:
  secret_key_base: 0f445f836eea468b7486f9977afdbbb3ddbf3c0066b8969298c88bb53f72973516b80dd5a8ff8a3885ec1423a78961f131c9c08e892810c91449540f741783ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
